--- Diary ---
@startuml
left to right direction
skinparam actorStyle awesome

actor Diaree <<Human>> #royalblue 
actor Visitor <<Human>> #lightblue

rectangle DayDiary #edfaf9 {
  usecase search as "Search DayDiary"
  usecase edit as "Edit Dayrec"
  usecase delete as "Delete Dayrec"
  usecase save as "Save Dayrec"
  usecase append as "Append File"
  usecase deleteFile as "Delete File"
  usecase read as "Read Dayrecs"

  usecase pin as "Pin a Dayrec"
  usecase mark as "Mark Text Section"

  usecase export as "Export Diary Section"

usecase warning as "Warning About\nUnsaved Changes"
}
Diaree  -> edit
Diaree  -> delete
Diaree  -> save
Diaree  -> search
Diaree  -> pin
Diaree  -> mark
Diaree  -> export
Diaree  -> append
Diaree  -> deleteFile
Diaree  -> read
warning -> Diaree

@enduml

--- User ---

@startuml
left to right direction
skinparam actorStyle awesome

actor Diaree <<Human>> #royalblue 
actor Visitor <<Human>> #lightblue

rectangle DayDiary #edfaf9 {
  usecase deleteUser as "Delete Diaree"
  usecase createUser as "Create Diaree"
  usecase chooseUser as "Choose Diaree"
  usecase login as "Log in"
  usecase logout as "Log out"
  usecase changeSettings as "Change Settings"
  usecase auth as "Authenticate"
}

Visitor -> createUser
Visitor  -> chooseUser
Diaree  -> deleteUser
deleteUser -> auth
Diaree  -> logout
Diaree  -> changeSettings

chooseUser -> login
login -> auth
@enduml

--- Statistics ---
@startuml
left to right direction
skinparam actorStyle awesome

actor Diaree <<Human>> #royalblue

rectangle DayDiary #edfaf9 {
  usecase viewStats as "View Statistics"

}

Diaree -> viewStats
@enduml