--- Diary ---
@startuml
left to right direction
skinparam actorStyle awesome

actor Diaree <<Human>> #royalblue 

rectangle DayDiary #edfaf9 {
  usecase search as "Search DayDiary"
  usecase edit as "Edit Dayrec"
  usecase delete as "Delete Dayrec"
  usecase save as "Save Dayrec"
  usecase append as "Append File"
  usecase deleteFile as "Delete File"
  usecase read as "Read Dayrecs"

  usecase unpin as "Unpin a Dayrec"
  usecase pin as "Pin a Dayrec"
  usecase mark as "Mark Text Section"

  usecase export as "Export Diary Section"

usecase message as "Application Message"
}
Diaree  -> edit
Diaree  -> delete
Diaree  -> save
Diaree  -> search
Diaree  -> unpin
Diaree  -> pin
Diaree  -> mark
Diaree  -> export
Diaree  -> append
Diaree  -> deleteFile
Diaree  -> read
message -> Diaree

@enduml
--- User ---
@startuml
left to right direction
skinparam actorStyle awesome

actor Diaree <<Human>> #royalblue 
actor Visitor <<Human>> #lightblue

rectangle DayDiary #edfaf9 {
  usecase createUser as "Create Diaree"
  usecase login as "Log in"
  usecase logout as "Log out"
  usecase changeSettings as "Change Settings"
  usecase auth as "Authenticate"
  usecase deleteUser as "Delete Diaree"
  usecase sysMsg as "Application Message"
}

Visitor -> createUser
Visitor  -> login
Diaree  -> deleteUser
deleteUser -> auth
Diaree  -> logout
Diaree  -> changeSettings
sysMsg  -> Visitor
sysMsg  -> Diaree

login -> auth
@enduml

--- Statistics ---
@startuml
left to right direction
skinparam actorStyle awesome

actor Diaree <<Human>> #royalblue

rectangle DayDiary #edfaf9 {
  usecase viewStats as "View Statistics"

}

Diaree -> viewStats
@enduml